# MD012/no-multiple-blanks : Multiple consecutive blank lines : https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md012.md
MD012:
  # Consecutive blank lines
  maximum: 2

# MD022/blanks-around-headings : Headings should be surrounded by blank lines : https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md022.md
MD022:
  # Blank lines above heading
  lines_above: 2
  # Blank lines below heading
  lines_below: 1

# MD033/no-inline-html : Inline HTML :
MD033: false
