repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        files: \.(js|jsx|ts|tsx|mjs|css|json|yaml|yml|astro|html)$

      - id: eslint-api
        name: eslint (api)
        entry: npx --prefix api eslint --config api/eslint.config.mjs --fix
        language: system
        files: ^api/.*\.(ts|mjs)$

      - id: eslint-app
        name: eslint (app)
        entry: npx --prefix app eslint --config app/eslint.config.mjs --fix
        language: system
        files: ^app/.*\.(ts|mjs|astro)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["-f"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: typecheck-api
        name: typecheck (api)
        entry: just api::typecheck
        language: system
        pass_filenames: false
        files: ^api/.*\.(ts|mjs)$
        stages: [pre-push]

      - id: typecheck-app
        name: typecheck (app)
        entry: just app::typecheck
        language: system
        pass_filenames: false
        files: ^app/.*\.(ts|mjs|astro)$
        stages: [pre-push]

      - id: test
        name: test
        entry: just test
        language: system
        pass_filenames: false
        stages: [pre-push]
