version: "3"

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env
    environment:
      - FLASK_ENV=developmemt
