"""
Django settings for thalida_com project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()


##################################################################################
# Base
##################################################################################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_#-p2gbfeq+)(@tg1w&@!0d7^7v&rnpdhv0*))&djpz)351f-i"

WSGI_APPLICATION = "thalida_com.wsgi.application"

##################################################################################
# Environment
##################################################################################

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

raw_env = os.getenv("DJANGO_ENV", "development")
cleaned_env = raw_env.lower().strip()
if cleaned_env not in ["development", "staging", "production"]:
    raise ValueError(
        f"ENV must be one of 'development', 'staging', or 'production'. Got {raw_env}."
    )
ENV = cleaned_env
IS_PRODUCTION_ENV = ENV == "production"
IS_STAGING_ENV = ENV == "staging"
IS_DEVELOPMENT_ENV = ENV == "development"

print(f"\n\033[1mCURRENT ENV: {ENV}\033[0m\n")

##################################################################################
# Apps
##################################################################################

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "corsheaders",
    "simple_history",
    # Local apps
    "core",
]


##################################################################################
# HOST & DOMAINS
##################################################################################
ALLOWED_HOSTS = []

CORS_ALLOWED_ORIGIN_REGEXES = []

if DEBUG:
    ALLOWED_HOSTS += [
        "localhost",
        "0.0.0.0",
        "127.0.0.1",
        "10.0.2.2",
        ".ngrok.app",
        ".ngrok-free.app",
        ".tunl.sh",
    ]

    CORS_ALLOWED_ORIGIN_REGEXES += [
        r"^http(s)?://localhost:3000$",
        r"^http(s)?://127.0.0.1:3000$",
    ]

##################################################################################
# Middleware
##################################################################################

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


##################################################################################
# Routes
##################################################################################
ROOT_URLCONF = "thalida_com.urls"


##################################################################################
# Templates
##################################################################################
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [f"{BASE_DIR}/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


##################################################################################
# Static files (CSS, JavaScript, Media)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
##################################################################################
STATIC_URL = "/static/"
MEDIA_URL = "/media/"


##################################################################################
# Database
##################################################################################
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://postgres:postgres@localhost:5432/postgres",
        conn_max_age=600,
    )
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

##################################################################################
# Authentication
##################################################################################

# User & Authentication
AUTH_USER_MODEL = "core.User"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


##################################################################################
# Internationalization & Localization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
##################################################################################

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True
